fix: removed project name from file source breadcrumbs (#1326)
radicle-dev/radicle-upstream pull request #1468
Opened 2020-12-06 20:46 UTC by finleygn

Fixes #1326

![image](https://user-images.githubusercontent.com/35561611/101291890-f2882c80-3803-11eb-9b5a-1cd343e2e38e.png)

2020-12-07 11:17 UTC, xla requested changes
Thanks a lot for contributing. Plese see https://github.com/radicle-dev/radicle-upstream/pull/1467#pullrequestreview-546051287

2020-12-07 15:18 UTC, cloudhead submitted a review, later dismissed
Thanks for contributing!

2020-12-07 15:27 UTC, xla requested changes
Great work, just a small clean up we can do.

2020-12-07 15:27 UTC, xla commented on ui/DesignSystem/Component/SourceBrowser/FileView/Blob.svelte
>    on:root
```suggestion
```

FileSource doesn't expose this anymore so we can remove it.

2020-12-07 15:27 UTC, xla commented on ui/DesignSystem/Component/SourceBrowser/FileView.svelte
> +    <Blob {view} on:root={onSelectRoot} on:select={onSelectCommit} />
```suggestion
    <Blob {view} on:select={onSelectCommit} />
```

The `on:root` binding is not necessary anymore as the origin event was removed.

2020-12-08 08:45 UTC, MeBrei approved these changes
Thanks for the contribution! ⭐

2020-12-08 08:45 UTC, MeBrei commented on ui/DesignSystem/Component/SourceBrowser/FileSource.svelte
>        </span>
The double nested `span` could now be removed.

2020-12-08 16:28 UTC, finleygn commented
all updated :)

2020-12-08 16:36 UTC, MeBrei approved these changes

2020-12-08 16:48 UTC, xla approved these changes
🌻 ✳️ 🍜 🏆

2020-12-15 16:40 UTC, rudolfs requested changes
I ran the specs locally with `yarn test` (as a workaround for https://github.com/radicle-dev/radicle-upstream/issues/1471), and three of them need to be updated before we can merge this:

```
  3 failing

  1) project source browsing
       source code browsing
         page view
           when we're looking at the project root
             when there is a README file
               shows the README file:
     AssertionError: Timed out retrying: Expected to find content: 'platinum / .i-am-well-hidden' within the element: <div> but never did.
      at Context.eval (http://localhost:64825/__cypress/tests?p=cypress/integration/project/source_browsing.spec.ts:242:30)

  2) project source browsing
       source code browsing
         source-tree
           doesn't interfere with the horizontal menu item active state:
     AssertionError: Timed out retrying: Expected to find content: 'platinum' within the element: <div.file-header.typo-semi-bold.svelte-1ub4xlw> but never did.
      at Context.eval (http://localhost:64825/__cypress/tests?p=cypress/integration/project/source_browsing.spec.ts:358:100)

  3) project source browsing
       source code browsing
         source-tree
           when clicking on a file name
             for filenames with special characters
               does not break:
     AssertionError: Timed out retrying: Expected to find content: 'platinum / special / -dash-' but never did.
      at Context.eval (http://localhost:64825/__cypress/tests?p=cypress/integration/project/source_browsing.spec.ts:431:68)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        24                                                                               │
  │ Passing:      19                                                                               │
  │ Failing:      3                                                                                │
  │ Pending:      2                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  3                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     46 seconds                                                                       │
  │ Spec Ran:     project/source_browsing.spec.ts                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

2021-02-10 18:24 UTC, juliendonck commented
Work is moved to #1609

2021-02-10 18:24 UTC, closed without merging