feat(ui): Label default branch in RevisionSelector
radicle-dev/radicle-upstream pull request #1503
Opened 2021-01-04 21:09 UTC by juliendonck

Adds a `default` badge to the revision selector for the default branch.

<img width="341" alt="Screenshot 2021-01-04 at 16 08 08" src="https://user-images.githubusercontent.com/2326909/103579860-1e500e00-4ea7-11eb-8973-80d3ff2110cf.png">  <img width="347" alt="Screenshot 2021-01-04 at 16 08 12" src="https://user-images.githubusercontent.com/2326909/103579858-1c864a80-4ea7-11eb-9831-234e7c196adb.png">

closes #1272

2021-01-04 21:11 UTC, juliendonck commented
Small one to start the new year and get back into the groove of things.

2021-01-04 21:11 UTC, juliendonck commented
@brandonhaslegs any color preferences?

2021-01-05 08:19 UTC, rudolfs requested changes
Aside from the enum capitalisation, this looks good!

2021-01-05 08:19 UTC, rudolfs commented on ui/src/badge.ts
> +  defaultBranch = "default",
```suggestion
  DefaultBranch = "default",
```

2021-01-05 08:19 UTC, rudolfs commented on ui/DesignSystem/Component/SourceBrowser/RevisionSelector/Entry.svelte
> +    <Badge variant={BadgeType.defaultBranch} />
```suggestion
    <Badge variant={BadgeType.DefaultBranch} />
```

2021-01-05 08:26 UTC, cloudhead approved these changes
Ye!

2021-01-05 16:00 UTC, juliendonck commented on ui/src/badge.ts
> +  defaultBranch = "default",
https://github.com/radicle-dev/radicle-upstream/pull/1503/commits/3d3e63d08a319bc7fef0d45fec73483dce64353f

2021-01-05 16:00 UTC, juliendonck commented on ui/DesignSystem/Component/SourceBrowser/RevisionSelector/Entry.svelte
> +    <Badge variant={BadgeType.defaultBranch} />
https://github.com/radicle-dev/radicle-upstream/pull/1503/commits/3d3e63d08a319bc7fef0d45fec73483dce64353f

2021-01-05 16:14 UTC, rudolfs approved these changes

2021-01-05 18:00 UTC, xla approved these changes
🏢 🍠 🗽 👜

2021-01-05 20:58 UTC, juliendonck commented
Changed the badge color to green to not clash with the maintainer badge.

<img width="1300" alt="Screenshot 2021-01-05 at 15 56 21" src="https://user-images.githubusercontent.com/2326909/103698018-b8c75480-4f6e-11eb-99a2-d21b4af8b147.png">

2021-01-05 21:57 UTC, rudolfs approved these changes

2021-01-06 08:26 UTC, xla approved these changes
👭 🌇 🙈 💝

2021-01-06 08:29 UTC, MeBrei approved these changes

2021-01-06 20:41 UTC, juliendonck commented
Can someone help me tomorrow to merge this, [since we're not allowed to press the button anymore](https://github.com/radicle-dev/radicle-decisions/blob/master/proposals/0003.md#merging-pull-requests)? Also can't we disable the buttons in the settings?

2021-01-07 15:50 UTC, closed without merging