move identifier
radicle-dev/radicle-upstream pull request #1723
Opened 2021-03-30 15:25 UTC by FintanH

I found the identifier module lying around in coco. I don't think it
needs to be there so I'm moving to api for now.

Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>

2021-03-30 15:30 UTC, xla requested changes
doc seems to be broken. Also does the identifier module need to be added to the api crate?

2021-03-31 08:43 UTC, FintanH commented
> Also does the identifier module need to be added to the api crate?

Can you elaborate on your question :) Not sure if you're saying if we should:
a. evaluate somewhere else it should go
b. it should stay in the coco realm
c. something else I'm not seeing

2021-03-31 08:48 UTC, xla commented
> Can you elaborate on your question :) Not sure if you're saying if we should:
> a. evaluate somewhere else it should go
> b. it should stay in the coco realm
> c. something else I'm not seeing

ha! None of the above, I was asking if you forgot to `git add` the actual identifier rs files, because they are not part of the change-set. :>

2021-03-31 08:50 UTC, FintanH commented
> ha! None of the above, I was asking if you forgot to git add the actual identifier rs files, because they are not part of the change-set. :>

Wait wut :thinking: It's moved here in this diff https://github.com/radicle-dev/radicle-upstream/pull/1723/files#diff-a771980c4efd0a18509d1fd44ae67ce45230afdc1ce081b09716242043288bd1

2021-03-31 08:52 UTC, xla commented
> Wait wut thinking It's moved here in this diff https://github.com/radicle-dev/radicle-upstream/pull/1723/files#diff-a771980c4efd0a18509d1fd44ae67ce45230afdc1ce081b09716242043288bd1

Disregard I can't read diffs. :facepalm:

2021-03-31 08:53 UTC, xla approved these changes
💱 🐙 🐬 🎼

2021-03-31 09:21 UTC, xla approved these changes
🏉 🔹 😃 🕵

2021-03-31 09:36 UTC, merged