feat(ui): tracking tab
radicle-dev/radicle-upstream pull request #776
Opened 2020-08-14 04:38 UTC by sarahscott

![Screen Shot 2020-08-13 at 9 34 29 PM](https://user-images.githubusercontent.com/2712962/90214379-1e8f2600-ddad-11ea-8540-830fb11c11f8.png)

2020-08-14 12:07 UTC, xla commented on ui/DesignSystem/Component/ProjectListItem.svelte
> +<script>
```suggestion
<script lang="ts">
```
All new components should be typescripted.

2020-08-14 12:07 UTC, xla commented on ui/Screen/Org/Projects.svelte
> +  const formatMetadata = orgProject =>
Should live in library code.

2020-08-14 12:09 UTC, xla commented on ui/Screen/Profile/Tracking.svelte
> +<script>
```suggestion
<script lang="ts">
```

2020-08-19 05:16 UTC, sarahscott commented
@brandonhaslegs #738 mitigates some of the feedback re: untracked project page and the `TrackToggle` button, so I'll ping you once it's merged and I can incorporate it here.

2020-08-21 00:59 UTC, sarahscott commented
@brandonhaslegs this has all functionality except that which will rely on the proxy api (e.g. removing untracked projects, navigating to them, etc).

2020-08-21 08:05 UTC, brandonhaslegs commented
Any way to test the notification when a project has been found?

2020-08-26 08:52 UTC, rudolfs approved these changes
Looks great! 🚀

2020-08-26 08:52 UTC, rudolfs commented on ui/Screen/Profile/Projects.svelte
> +  console.log(session);
```suggestion
```

2020-08-26 08:52 UTC, rudolfs commented on ui/src/animation.ts
> +export const fadeDuration = 200;
We already have a `config.ts` maybe we can put this there?

2020-08-26 09:45 UTC, xla requested changes
Still looking rather good, I'm not quite sure what the meaning of the `Hoverable` component is, could you outline how it's meant to be used across the app?

2020-08-27 20:58 UTC, sarahscott commented on ui/DesignSystem/Component/TrackToggle.svelte
> +  // warning variant implies consequences of untracking are more severe
It's not code-related; it's to provide context for what the variant looks like visually and why it exists. Probably makes more sense to just put this in the design guide.

2020-08-27 20:59 UTC, sarahscott commented
@xla `Hoverable` is `Copyable` for hovering.

2020-08-27 21:56 UTC, xla requested changes
Looks like `animation.ts` is orphaned now and can go, also not sure we should add any more to the existing org tests, given we removed the orgs for now.

2020-08-27 21:56 UTC, xla commented on ui/src/org.test.ts
>  import { get } from "svelte/store";
```suggestion
import { get } from "svelte/store";

import * as org from "./org";
import { idValidationStore } from "./id";
import { ValidationStatus } from "./validation";
```

2020-08-27 22:32 UTC, sarahscott commented
Oh woops 😆 yeah `animation.ts` can definitely go. Should we keep the org unit tests at all? I'd say they provide some nice jest + svelte examples but are otherwise irrelevant if we're not bringing orgs back.

2020-08-28 06:48 UTC, xla commented
> Oh woops laughing yeah `animation.ts` can definitely go. Should we keep the org unit tests at all? I'd say they provide some nice jest + svelte examples but are otherwise irrelevant if we're not bringing orgs back.

Good point, let's leave them until we have more certainty what the future holds for the registry.

2020-08-28 06:49 UTC, xla approved these changes
🗂 4️⃣ ☀️ 👂

2020-08-28 07:45 UTC, rudolfs approved these changes

2020-08-28 07:46 UTC, merged