style(ui): refresh icons
radicle-dev/radicle-upstream pull request #806
Opened 2020-08-21 15:09 UTC by rudolfs

<img width="1152" alt="Screenshot 2020-08-24 at 17 42 21" src="https://user-images.githubusercontent.com/158411/91065793-35493e80-e631-11ea-9d0b-0e8c11dac20a.png">

![preview](https://user-images.githubusercontent.com/158411/91062227-bc47e800-e62c-11ea-9f4f-ea508644f3f5.gif)

- [x] update all icons according to [new style guide](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=3554%3A17)
- [x] convert all icons to a unified size - 24px x 24px
- [x] make naming consistent across style guide in Figma and code
- [x] list all icons in design system guide programmatically (so we don't have to update it whenever we add/remove or change icons)
- [x] make icons copyable in the design system guide

Closes: https://github.com/radicle-dev/radicle-upstream/issues/797.

2020-08-24 14:55 UTC, rudolfs commented on ui/DesignSystem/Component/EmptyState.svelte
> +  export let illustration = "plant"; // eyes | plant | telescope | tent
Yeah, I wanted to use TS, but couldn't figure out how to get it to work with Svelte. We should probably do this in a separate PR and across the whole codebase.

2020-08-24 14:56 UTC, rudolfs commented on ui/Screen/SendFunds.svelte
> +              variant="rad-big"
Moved all the icon variants into separate components.

2020-08-24 15:37 UTC, brandonhaslegs approved these changes

2020-08-24 16:50 UTC, sarahscott commented on ui/DesignSystem/Component/EmptyState.svelte
> +  export let illustration = "plant"; // eyes | plant | telescope | tent
You can use typescript in svelte so long as the typescript is in a `.ts` file - e.g.:

`validation.ts`
```typescript
export enum ValidationStatus {
  NotStarted = "NOT_STARTED",
  Loading = "LOADING",
  Error = "ERROR",
  Success = "SUCCESS",
}
```

`Text.svelte`
```typescript
<input
    data-cy={dataCy}
    class:invalid={validation && validation.status === ValidationStatus.Error}
    class:left-item={showLeftItem}
    {placeholder}
    bind:value
    {disabled}
    on:change
    on:input />
```

2020-08-25 08:15 UTC, rudolfs commented on ui/DesignSystem/Component/EmptyState.svelte
> +  export let illustration = "plant"; // eyes | plant | telescope | tent
Would we then have a `ComponentTypes.ts` file and put all the variants in there?

2020-08-25 08:57 UTC, xla approved these changes
Besides the improvements to variant usage, this looks good.

🚊 🛰 💜 🐢

2020-08-25 08:57 UTC, xla commented on ui/DesignSystem/Component/EmptyState.svelte
> +  export let illustration = "plant"; // eyes | plant | telescope | tent
It would probably be `illustration.ts` which exports an `enum Variant`.

2020-08-25 09:01 UTC, MeBrei requested changes
Looks good to me!
I would also extract the variants as @sarahscott suggested.

2020-08-25 09:32 UTC, MeBrei approved these changes
🎉

2020-08-25 10:06 UTC, brandonhaslegs requested changes
- [x] `<Icon.Info />` should be `<Icon.InfoCircle />`
- [x] `<Icon.InfoNoCircle />` should be `<Icon.Info />`
- [ ] `<Icon.CurrencyDollarLarge />` should be USD instead of Dollar? "Dollar" is used in many currencies (Canadian Dollar for example). I think the currency in general should use the three letter acronym. So USD, EUR, and RAD.
- [ ] Remove `Large` from all icons. Only have `Small` in the case where there is a second size.
- [ ] Change `<Icon.Roadmap />` to `<Icon.Road />` because it's more neutral.
- [ ] Remove all with `NoCircle`. There should only be Circle as an add on if there's a circle around the icon.
- [ ] We were missing the `LockSmall` icon.
- [ ] Ellipsis is spelled with an i, not an e.

2020-08-25 10:23 UTC, rudolfs commented on ui/DesignSystem/Component/EmptyState.svelte
> +  export let illustration = "plant"; // eyes | plant | telescope | tent
https://github.com/radicle-dev/radicle-upstream/pull/806/commits/abe4961f630f2a9716f9168888153e362742af8d

2020-08-25 10:23 UTC, rudolfs commented on ui/DesignSystem/Component/EmptyState/Illustration.svelte
> +  style={`flex-shrink: 0;${style ? style : ''}`}
https://github.com/radicle-dev/radicle-upstream/pull/806/commits/260d4fc919f582be1237854deb781a815f92e56f

2020-08-25 10:36 UTC, brandonhaslegs approved these changes

2020-08-25 10:54 UTC, MeBrei approved these changes

2020-08-25 10:58 UTC, merged