Add maintainer badge
radicle-dev/radicle-upstream pull request #818
Opened 2020-08-25 16:58 UTC by cloudhead

![2020-08-25-184130_352x210_scrot](https://user-images.githubusercontent.com/40774/91204886-f97fa900-e704-11ea-90db-4846fc302818.png)
![2020-08-25-184138_532x400_scrot](https://user-images.githubusercontent.com/40774/91204887-fab0d600-e704-11ea-8814-69ac75d26381.png)

This adds the maintainer badge to maintainers in the revision selector and the projects page.

2020-08-25 19:14 UTC, xla submitted a review, later dismissed
🌵 ♌️ 🌊 🐏

2020-08-26 07:50 UTC, rudolfs requested changes
Looks like you forgot to add:

```
import { getContext } from "svelte";
const { registrationFee } = getContext("session");
```

in `Project.svelte`.

<img width="441" alt="Screenshot 2020-08-26 at 09 48 05" src="https://user-images.githubusercontent.com/158411/91276224-88caa200-e781-11ea-8954-e8893022d358.png">

That's also why the build is failing.

2020-08-26 08:07 UTC, xla commented
Looks like merge snafu from #817.

2020-08-26 10:32 UTC, rudolfs approved these changes

2020-08-26 10:42 UTC, brandonhaslegs requested changes

2020-08-26 10:42 UTC, brandonhaslegs commented on ui/DesignSystem/Component/Badge.svelte
> +    color: var(--color-primary);
The color should be `--color-secondary` and background should be `--color-secondary-level-1` according to Figma.
![image](https://user-images.githubusercontent.com/4406983/91294203-72c8db80-e799-11ea-8e90-21dbe085c394.png)

2020-08-26 10:45 UTC, brandonhaslegs commented on ui/DesignSystem/Component/Badge.svelte
> +    padding: 0.125rem 0.25rem;
The height of the badge should be 24px. It's currently 21.
![image](https://user-images.githubusercontent.com/4406983/91294491-e5d25200-e799-11ea-83de-f960fce1acec.png)

2020-08-26 12:06 UTC, rudolfs approved these changes

2020-08-26 12:09 UTC, brandonhaslegs approved these changes

2020-08-26 12:22 UTC, merged