Profile page overhaul
radicle-dev/radicle-upstream pull request #839
Opened 2020-08-28 09:59 UTC by MeBrei

Closes #833

2020-08-28 12:11 UTC, rudolfs approved these changes

2020-08-28 14:04 UTC, brandonhaslegs requested changes
The URN should still have a background on hover. Not sure if this is covered in this PR, but just wanted to say. It should have `var(--color-foreground-level-2)` on hover. Otherwise looks good!

2020-08-28 14:30 UTC, MeBrei commented on ui/DesignSystem/Component/Urn.svelte
> +            style="line-height: 25px;">
I added this so that the lines do not jump up and down on hover. @rudolfs do you know a more elegant way to do it?

2020-08-28 14:45 UTC, rudolfs commented
The content shouldn't jump around on hover at all. We might need to refactor the components a bit.

![Aug-28-2020 16-37-45](https://user-images.githubusercontent.com/158411/91580694-c11edb80-e94d-11ea-8f58-af34371a1f80.gif)

2020-09-01 11:35 UTC, rudolfs approved these changes

2020-09-01 11:51 UTC, brandonhaslegs requested changes
Not sure if this is related to this PR, but these URNs on the following tab should not have the copy icon visible until hover.
![image](https://user-images.githubusercontent.com/4406983/91844893-8a500a80-ec58-11ea-9d89-57ba78bf23cd.png)

---

2020-09-01 12:17 UTC, MeBrei commented
> Not sure if this is related to this PR, but these URNs on the following tab should not have the copy icon visible until hover.


@brandonhaslegs fixed!

2020-09-01 12:20 UTC, rudolfs approved these changes

2020-09-01 12:34 UTC, brandonhaslegs approved these changes

2020-09-01 12:40 UTC, merged