rustfmt: Enable merge_imports
radicle-dev/radicle-upstream pull request #883
Opened 2020-09-09 08:33 UTC by NunoAlexandre

Enable Rust cargo fmt `merge_imports`.

**Why**:

- This is enabled on `link`, therefore enabling it here as well reduces the gap between the two projects
- I have come to appreciate this on `link`, as it reduces the amount of duplicated `import <crate>::` lines
- Neater imports

2020-09-09 09:25 UTC, cloudhead submitted a review, later dismissed

2020-09-09 09:50 UTC, xla requested changes
Strongly opposed to this change, it makes it way harder to edit the imports and trace them quickly.

2020-09-09 09:53 UTC, MeBrei submitted a review, later dismissed

2020-09-09 11:06 UTC, FintanH commented
>  it makes it way harder to edit the imports and trace them quickly.

Could you expand on these points?

From my point of view, editing doesn't seem hard. You add the new `sub-crate`, `function`, or `type` into the list.
And for tracing, they're still alphabetical and grouped under their common structure.
That's just my opinion on those two points and would appreciate to get an insight on what annoyances you see :)

2020-09-12 00:16 UTC, sarahscott approved these changes
i'm a fan of consistency; if this is how it's done in link i see no reason for it to be different in proxy.

but i am neither 'strongly opposed' nor 'strongly in favor', fwiw.

2020-09-14 08:29 UTC, xla approved these changes

2020-09-14 08:34 UTC, merged