feat(ui): project name formatting
radicle-dev/radicle-upstream pull request #938
Opened 2020-09-18 22:41 UTC by sarahscott

Closes #529

2020-09-19 15:01 UTC, NunoAlexandre reviewed
just two small comments :field_hockey:

2020-09-20 15:23 UTC, xla reviewed
Nothing to add to @NunoAlexandre observations, happy to approve once addressed. Test needs to be looked at.

2020-09-21 07:54 UTC, rudolfs commented
I'm wondering whether we should also add this to the handle input in onboarding to keep things consistent, as it also disallows spaces. \cc @brandonhaslegs @juliendonck 

<img width="627" alt="Screenshot 2020-09-21 at 09 53 43" src="https://user-images.githubusercontent.com/158411/93743448-5d0bd200-fbf0-11ea-8c24-e4022699e4d8.png">

2020-09-21 08:21 UTC, juliendonck commented
> I'm wondering whether we should also add this to the handle input in onboarding as well to keep things consistent. That input also disallows spaces. \cc @brandonhaslegs @juliendonck
> 
> <img alt="Screenshot 2020-09-21 at 09 53 43" width="627" src="https://user-images.githubusercontent.com/158411/93743448-5d0bd200-fbf0-11ea-8c24-e4022699e4d8.png">

yes :)

2020-09-21 08:37 UTC, FintanH commented on ui/src/project.ts
> +export const formatFromExistingRepo = (path: string) =>
And better still, you should represent the newly extracted name with a type that says you did so. That way you can't mix it up with other strings :grin:

2020-09-21 09:26 UTC, xla commented on ui/src/project.ts
> +export const formatFromExistingRepo = (path: string) =>
![type police](https://media1.giphy.com/media/81xwEHX23zhvy/200.gif)

2020-09-21 09:46 UTC, FintanH commented on ui/src/project.ts
> +export const formatFromExistingRepo = (path: string) =>
Put a type on it meow

2020-09-22 02:05 UTC, sarahscott commented on ui/src/project.ts
> +export const formatFromExistingRepo = (path: string) =>
Would be cool but TypeScript would actually just treat this as a `string` and wouldn't throw an error if I treated it as any other "type" of this form: 
```
type RepoPath = string;
```

There are some interesting approaches to `newtypes` in TS though - could be interesting to explore:
https://www.everythingfrontend.com/posts/newtype-in-typescript.html
https://github.com/gcanti/newtype-ts

2020-09-22 07:58 UTC, rudolfs requested changes

2020-09-22 07:58 UTC, rudolfs commented on cypress/integration/project_creation.spec.js
> +    context.only("name", () => {
```suggestion
    context("name", () => {
```

Our eslint plugin has failed us :( This should have failed on CI.

2020-09-22 08:33 UTC, FintanH commented on ui/src/project.ts
> +export const formatFromExistingRepo = (path: string) =>
We could have a class with a single field, no?

2020-09-22 08:35 UTC, rudolfs commented
Other than the skipped tests works and looks great!

2020-09-23 06:56 UTC, rudolfs approved these changes

2020-09-23 06:57 UTC, MeBrei approved these changes

2020-09-23 06:59 UTC, merged