fix(ui): improve identity and project name validation
radicle-dev/radicle-upstream pull request #953
Opened 2020-09-23 14:16 UTC by MeBrei

Closes #949

2020-09-23 14:43 UTC, rudolfs approved these changes

2020-09-23 14:43 UTC, rudolfs commented on ui/src/validation.ts
> +    );
```suggestion
    return `Your ${options.valueName} should start with a letter or a number.`;
```

2020-09-23 15:09 UTC, rudolfs submitted a review, later dismissed

2020-09-23 23:49 UTC, sarahscott commented on ui/src/validation.ts
> +interface firstHandleCharOptions {
```suggestion
interface FirstHandleCharOptions {
```

2020-09-23 23:50 UTC, sarahscott commented on ui/src/validation.ts
> +  firstHandleChar?: firstHandleCharOptions;
Alternatively, you could skip making a separate `interface` and just do:
```suggestion
  firstHandleChar?: {
      valueName: string
  };
```

2020-09-23 23:52 UTC, sarahscott requested changes
Looking good apart from the `interface` thing - should be capitalized or built into the existing `FormatConstraints` ⭐

2020-09-24 07:19 UTC, rudolfs approved these changes

2020-09-24 21:01 UTC, sarahscott approved these changes

2020-09-24 21:02 UTC, merged